### ISSUE TITLE
AEC Filter

### ISSUE THREAD

**Issue by StuartIanNaylor** [ozangerger/DigitalFilters#1]
Maybe for the next project as opensource AI would really benefit from some new low load SoC based filter methods :)

**Comment by ozangerger** [comment]
Thanks for your comment Stuart. Right now, I'm working on multiple sensor fusion projects and I believe this'll take quite some time. However, I would really enjoy working on new methods and have a look at them.

**Comment by StuartIanNaylor** [comment]
The main 2 are speexdsp and webrtc_audio_processing.

PS sensor fusion is that like beamforming as thats of much interest as well?
